engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    exclude_paths:
    - spec/
  fixme:
    enabled: true
  rubocop:
    enabled: true
    exclude_fingerprints:
    # Ignoring long method length for Analyzer#run
    - b18e3ac8a9b02f26a0b769f67d758761
    # Ignoring long method length for UnpatchedGemIssue#to_json
    - 60d15e0a35747ad1c4a7dfe29301f3bd
    # Ignoring long method length for InsecureSourceIssue#to_json
    - f861a7b796b8b07217f4a75db9bb631d
ratings:
  paths:
  - "**.rb"
exclude_paths:
  - "spec/fixtures"
