AllCops:
  TargetRubyVersion: 2.2
Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Rails/TimeZone:
  Enabled: false

SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/**/*'

Style/IfUnlessModifier:
  Enabled: false

Style/DotPosition:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': []
    '%W': []
