source "https://rubygems.org"

gem "rails", "~> 4.2.5"
gem "devise", "~> 3.4.0"
gem "jquery-rails", "~> 3.1.2"
gem "uglifier", "~> 2.5.3"
gem "simple_form", git: "git@github.com:plataformatec/simple_form.git"
