version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make test-image
      - run: make test

  release_images:
    machine:
      docker_layer_caching: true
    working_directory: ~/codeclimate/codeclimate-bundler-audit
    steps:
      - checkout
      - run:
          name: Validate owner
          command: |
            if [ "$CIRCLE_PROJECT_USERNAME" -ne "codeclimate" ]
            then
              echo "Skipping release for non-codeclimate branches"
              circleci step halt
            fi
      - run: make image
      - run: echo "$GCR_JSON_KEY" | docker login -u _json_key --password-stdin us.gcr.io
      - run: bin/deploy


workflows:
  version: 2
  build_deploy:
    jobs:
      - build_and_test
      - release_images:
          requires:
            - build_and_test
          filters:
            branches:
              only: /master|channel\/[\w-]+/
notify:
  webhooks:
    - url: https://cc-slack-proxy.herokuapp.com/circle
